/* find most fma-divergent block/row column of dec16 for the probe (rel metric, harness-like) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdint.h>
#define BLOCKS 18
#define EL 16384
typedef struct { uint32_t magic, version, n, mask, blocks; } Hdr;
static float f16ToF32(uint32_t h){uint32_t s=(h>>15)&1,e=(h>>10)&31,m=h&1023,b;
if(e==0){if(!m)b=s<<31;else{uint32_t mm=m,ss=0;while(!(mm&512)){mm<<=1;ss++;}b=(s<<31)|((112-ss)<<23)|((mm&511)<<14);}}
else if(e==31)b=(s<<31)|(255<<23)|(m<<13);else b=(s<<31)|((e+112)<<23)|(m<<13);
float v;memcpy(&v,&b,4);return v;}
#define RD16(p) ((uint32_t)(p)[0]|((uint32_t)(p)[1]<<8))
#define RD32(p) ((uint32_t)(p)[0]|((uint32_t)(p)[1]<<8)|((uint32_t)(p)[2]<<16)|((uint32_t)(p)[3]<<24))
int main(int argc,char**argv){
  FILE*f=fopen(argv[1],"rb");fseek(f,0,SEEK_END);size_t n=(size_t)ftell(f);fseek(f,0,SEEK_SET);
  uint8_t*o=malloc(n);fread(o,1,n,f);fclose(f);
  const size_t BOFF=4096+256+256+2*EL+4*EL+4*EL+2*EL+2*EL,base=sizeof(Hdr)+131072;
  const size_t O_DEC=4096+512,O_SUH=4096,O_TMP=4096+512+2*EL;
  const float HS=0.08838834764831845f;
  double best=0;int bb=0,br=0;
  for(int b=0;b<BLOCKS;b++)for(int r=0;r<128;r++){
    float as=0,af=0;
    for(int k=0;k<128;k++){
      float he=((__builtin_popcount(r&k)&1)?-HS:HS);
      float xv=f16ToF32(RD16(o+base+(size_t)b*BOFF+O_DEC+2*(size_t)(k*128+r)));
      as=as+he*xv; af=fmaf(he,xv,af);
    }
    float suh=f16ToF32(RD16(o+base+(size_t)b*BOFF+O_SUH+2*(size_t)r));
    float ts=as*suh, tf=af*suh;
    uint32_t eb=RD32(o+base+(size_t)b*BOFF+O_TMP+4*(size_t)(r*128+r));
    float er; memcpy(&er,&eb,4);
    double d=fabs((double)ts-(double)tf)/fmax(fabs((double)er),1e-30);
    if(d>best){best=d;bb=b;br=r;}
  }
  printf("best block %d row %d rel %.3e\n",bb,br,best);
  FILE*g=fopen("../probe/probe_col.h","w");
  fprintf(g,"// generated by findcol.c from oracle.bin: dec16 column, block %d row %d\n",bb,br);
  fprintf(g,"#define COL_RAW ");
    for(int k=0;k<128;k++){
      size_t off=base+(size_t)bb*BOFF+O_DEC+2*(size_t)(k*128+br);
      if(k%16==15&&k!=127) fprintf(g,"0x%02X%02X,\\\n",o[off+1],o[off]);
      else fprintf(g,"0x%02X%02X%s",o[off+1],o[off],k==127?"\n":",");
    }
  uint32_t sb=RD16(o+base+(size_t)bb*BOFF+O_SUH+2*(size_t)br);
  float sv=f16ToF32(sb); uint32_t sw; memcpy(&sw,&sv,4);
  fprintf(g,"#define PB_BLOCK %du\n#define PB_ROW %du\n",bb,br);
  fprintf(g,"#define PB_SUH_BITS 0x%08Xu // suh f16 0x%04X\n",sw,sb);
  fclose(g);
  /* reference tmp value at [r][r] for cross-check */
  uint32_t eb=RD32(o+base+(size_t)bb*BOFF+O_TMP+4*(size_t)(br*128+br));
  float er;memcpy(&er,&eb,4);printf("oracle tmp[block][row][row] = %.9e (0x%08X)\n",er,eb);
  return 0;
}
